name: Scheduled with inputs

#TODO: temporary
on:
  schedule:
    - cron: '* * * * *'
#  workflow_dispatch:
#    inputs:
#      number:
#        type: number
#        default: 1
#        required: false

jobs:
  echo:
    uses: ./.github/workflows/echo.yml
    with:
      number: ${{ fromJson(inputs.number || 99) }}
