name: Scheduled with inputs

#TODO: temporary
on:
  schedule:
    - cron: '25,30,35,40 * * * *'
  workflow_dispatch:
    inputs:
      number:
        type: number
        default: 1
        required: false

jobs:
  echo:
    uses: ./.github/workflows/echo.yml
    with:
      number: ${{ inputs.number || 99 }}
