name: Workflow dispatch with no default

#TODO: temporary
on:
  workflow_dispatch:
    inputs:
      number:
        type: number
        required: false

jobs:
  echo:
    uses: ./.github/workflows/echo.yml
    with:
      number: ${{ fromJson(inputs.number || 99) }}
